from sqlalchemy import create_engine
import mysql.connector
import pandas as pd

engine = create_engine("mysql+mysqlconnector://Savinay:savinay@35.185.177.170/WorldMarkets")
currencies = create_engine("mysql+mysqlconnector://Savinay:savinay@35.185.177.170/Currencies")
commodities = create_engine("mysql+mysqlconnector://Savinay:savinay@35.185.177.170/Commodities")

BSE = pd.read_csv("Data/BSE.csv")
AORD = pd.read_csv("Data/AORD.csv")
DJI = pd.read_csv("Data/DJI.csv")
FCHIX = pd.read_csv("Data/FCHIX.csv")
FTSE = pd.read_csv("Data/FTSE.csv")
GDAXI = pd.read_csv("Data/GDAXI.csv")
GSPC = pd.read_csv("Data/GSPC.csv")
HSI = pd.read_csv("Data/HSI.csv")
KLSE = pd.read_csv("Data/KLSE.csv")
KS11 = pd.read_csv("Data/KS11.csv")
KSLE = pd.read_csv("Data/KSLE.csv")
N225 = pd.read_csv("Data/N225.csv")
PSEI = pd.read_csv("Data/PSEI.csv")
TWII = pd.read_csv("Data/TWII.csv")
NSEI = pd.read_csv("Data/^NSEI.csv")

EURINR = pd.read_csv("Currencies/EURINR.csv")
EURUSD = pd.read_csv("Currencies/EURUSD.csv")
GBPUSD = pd.read_csv("Currencies/GBPUSD.csv")
JPYINR = pd.read_csv("Currencies/JPYINR.csv")
USDINR = pd.read_csv("Currencies/USDINR.csv")
USDJPY = pd.read_csv("Currencies/USDJPY.csv")
GBPINR = pd.read_csv("Currencies/GBPINR.csv")

Aluminium = pd.read_csv("Commodities/Aluminium.csv")
BrentCrude = pd.read_csv("Commodities/BrentCrude.csv")
Cocoa = pd.read_csv("Commodities/Cocoa.csv")
Coffee = pd.read_csv("Commodities/Coffee.csv")
Copper = pd.read_csv("Commodities/Copper.csv")
Corn = pd.read_csv("Commodities/Corn.csv")
Cotton = pd.read_csv("Commodities/Cotton.csv")
CrudeOil = pd.read_csv("Commodities/CrudeOil.csv")
Gasoline = pd.read_csv("Commodities/Gasoline.csv")
Gold = pd.read_csv("Commodities/Gold.csv")
IronOre = pd.read_csv("Commodities/IronOre.csv")
Lead = pd.read_csv("Commodities/Lead.csv")
NaturalGas = pd.read_csv("Commodities/NaturalGas.csv")
Palladium = pd.read_csv("Commodities/Palladium.csv")
Platinum = pd.read_csv("Commodities/Platinum.csv")
Silver = pd.read_csv("Commodities/Silver.csv")
Soyabean = pd.read_csv("Commodities/Soyabean.csv")
Sugar = pd.read_csv("Commodities/Sugar.csv")
Tin = pd.read_csv("Commodities/Tin.csv")
Wheat = pd.read_csv("Commodities/Wheat.csv")
Zinc = pd.read_csv("Commodities/Zinc.csv")
Nickel = pd.read_csv("Commodities/Nickel.csv")


print("Importing Currencies to SQL....")
EURINR.to_sql(name='EURINR',con=currencies,if_exists='replace',index=False)
EURUSD.to_sql(name='EURUSD',con=currencies,if_exists='replace',index=False)
GBPINR.to_sql(name='GBPINR',con=currencies,if_exists='replace',index=False)
GBPUSD.to_sql(name='GBPUSD',con=currencies,if_exists='replace',index=False)
JPYINR.to_sql(name='JPYINR',con=currencies,if_exists='replace',index=False)
USDINR.to_sql(name='USDINR',con=currencies,if_exists='replace',index=False)
USDJPY.to_sql(name='USDJPY',con=currencies,if_exists='replace',index=False)
print("Done")


print("Importing World Markets to SQL....")
BSE.to_sql(name='BSE',con=engine,if_exists='replace',index=False)
AORD.to_sql(name='AORD',con=engine,if_exists='replace',index=False)
DJI.to_sql(name='DJI',con=engine,if_exists='replace',index=False)
FCHIX.to_sql(name='FCHIX',con=engine,if_exists='replace',index=False)
FTSE.to_sql(name='FTSE',con=engine,if_exists='replace',index=False)
GDAXI.to_sql(name='GDAXI',con=engine,if_exists='replace',index=False)
GSPC.to_sql(name='GSPC',con=engine,if_exists='replace',index=False)
HSI.to_sql(name='HSI',con=engine,if_exists='replace',index=False)
KLSE.to_sql(name='KLSE',con=engine,if_exists='replace',index=False)
N225.to_sql(name='N225',con=engine,if_exists='replace',index=False)
PSEI.to_sql(name='PSEI',con=engine,if_exists='replace',index=False)
TWII.to_sql(name='TWII',con=engine,if_exists='replace',index=False)
KS11.to_sql(name='KS11',con=engine,if_exists='replace',index=False)
NSEI.to_sql(name='NSEI',con=engine,if_exists='replace',index=False)
print("Done")

print("Importing Commodities to SQL....")
Aluminium.to_sql(name='Aluminium',con=commodities,if_exists='replace',index=False)
BrentCrude.to_sql(name='BrentCrude',con=commodities,if_exists='replace',index=False)
Cocoa.to_sql(name='Cocoa',con=commodities,if_exists='replace',index=False)
Coffee.to_sql(name='Coffee',con=commodities,if_exists='replace',index=False)
Copper.to_sql(name='Copper',con=commodities,if_exists='replace',index=False)
Corn.to_sql(name='Corn',con=commodities,if_exists='replace',index=False)
Cotton.to_sql(name='Cotton',con=commodities,if_exists='replace',index=False)
CrudeOil.to_sql(name='CrudeOil',con=commodities,if_exists='replace',index=False)
Gasoline.to_sql(name='Gasoline',con=commodities,if_exists='replace',index=False)
Gold.to_sql(name='Gold',con=commodities,if_exists='replace',index=False)
IronOre.to_sql(name='IronOre',con=commodities,if_exists='replace',index=False)
Lead.to_sql(name='Lead',con=commodities,if_exists='replace',index=False)
NaturalGas.to_sql(name='NaturalGas',con=commodities,if_exists='replace',index=False)
Nickel.to_sql(name='Nickel',con=commodities,if_exists='replace',index=False)
Palladium.to_sql(name='Palladium',con=commodities,if_exists='replace',index=False)
Platinum.to_sql(name='Platinum',con=commodities,if_exists='replace',index=False)
Silver.to_sql(name='Silver',con=commodities,if_exists='replace',index=False)
Soyabean.to_sql(name='Soyabean',con=commodities,if_exists='replace',index=False)
Sugar.to_sql(name='Sugar',con=commodities,if_exists='replace',index=False)
Tin.to_sql(name='Tin',con=commodities,if_exists='replace',index=False)
Wheat.to_sql(name='Wheat',con=commodities,if_exists='replace',index=False)
Zinc.to_sql(name='Zinc',con=commodities,if_exists='replace',index=False)

print("Done")